#!/usr/bin/env zsh

# golang
export GOPATH=$HOME/WorkSpaces/go
# [[ $PATH =~ $GOPATH/bin ]] || PATH=$(go env GOPATH)/bin:$PATH

export JDK_HOME=/usr/lib/jvm/default
export JAVA_HOME=$JDK_HOME

# yarn
if (( $+commands[yarn] )); then
    [[ $PATH =~ $HOME/.yarn/bin ]] || PATH=$(yarn global bin):$PATH
fi

export PYTHONUSERBASE=$HOME/.local

if [[ $OSTYPE == darwin* ]]; then
    export LC_ALL=en_US.UTF-8
    export LANG=en_US.UTF-8
    local gnu_tools=(coreutils findutils gnu-tar gnu-sed gawk gnutls gnu-indent gnu-getopt grep)
    local libexec_arr=('/usr/local/opt/' ' ' '/libexec/gnubin')
    for tool in $gnu_tools; do
        libexec_arr[2]=$tool
        local dir=${(j..)libexec_arr}
        if [[ -d $dir ]]; then
            PATH="$dir:$PATH"
        fi
    done
fi

# path
[[ $PATH =~ $HOME/.local/bin ]] || PATH=$HOME/.local/bin:$PATH
export PATH

# emacs mode
bindkey -e

# tabs size
tabs 4

if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager \
        (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

ZSH_LPLUG_DIR=${XDG_CONFIG_HOME:-$HOME/.config}/zsh/lplug
source ~/.zinit/bin/zinit.zsh

ZSH_AUTOSUGGEST_USE_ASYNC=1
ZSH_AUTOSUGGEST_MANUAL_REBIND=1
zinit wait lucid for \
    zdharma-continuum/fast-syntax-highlighting \
    atload='!_zsh_autosuggest_start' zsh-users/zsh-autosuggestions \
    blockf zsh-users/zsh-completions

_ZL_NO_ALIASES=1
zinit lucid wait for \
    as='program' src='z.lua.plugin.zsh' skywind3000/z.lua \
    hlissner/zsh-autopair

zinit light-mode for \
    mafredri/zsh-async \
    kevinhwang91/zsh-tmux-capture

source $ZSH_LPLUG_DIR/completion.zsh
source $ZSH_LPLUG_DIR/misc.zsh
source $ZSH_LPLUG_DIR/color.zsh
source $ZSH_LPLUG_DIR/history.zsh
source $ZSH_LPLUG_DIR/alias-function.zsh
source $ZSH_LPLUG_DIR/theme.zsh
source $ZSH_LPLUG_DIR/git-prompt.zsh
source $ZSH_LPLUG_DIR/tmux.zsh
source $ZSH_LPLUG_DIR/fzf-plugin.zsh

# python prompt toolkit color depth
export PROMPT_TOOLKIT_COLOR_DEPTH=DEPTH_24_BIT

# ranger
if (( $+commands[ranger] )); then
    export RANGER_LOAD_DEFAULT_RC=FALSE
fi

# neovim
if (( $+commands[nvim] )); then
    export EDITOR=nvim
    export MANPAGER='nvim +Man!'
    export DIFFPROG='nvim -d'
fi

# bat
if (( $+commands[bat] )); then
    export BAT_THEME=TwoDark
    export BAT_STYLE=plain
fi
