#!/usr/bin/env zsh

# yarn
[[ $PATH =~ $HOME/.yarn/bin ]] || PATH=$(yarn global bin):$PATH

# golang
export GOPATH=$HOME/WorkSpaces/go
# [[ $PATH =~ $GOPATH/bin ]] || PATH=$(go env GOPATH)/bin:$PATH

# path
[[ $PATH =~ $HOME/.local/bin ]] || PATH=$HOME/.local/bin:$PATH
export PATH

export JDK_HOME=/usr/lib/jvm/default

# emacs mode
bindkey -e

# tabs size
tabs 4

if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager \
        (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

ZSH_LPLUG_DIR=${XDG_CONFIG_HOME:-$HOME/.config}/zsh/lplug
source ~/.zinit/bin/zinit.zsh

ZSH_AUTOSUGGEST_USE_ASYNC=1
ZSH_AUTOSUGGEST_MANUAL_REBIND=1
zinit wait lucid for \
    zdharma/fast-syntax-highlighting \
    atload='!_zsh_autosuggest_start' zsh-users/zsh-autosuggestions \
    blockf zsh-users/zsh-completions

_ZL_NO_ALIASES=1
zinit lucid wait for \
    as='program' src='z.lua.plugin.zsh' skywind3000/z.lua \
    hlissner/zsh-autopair

zinit light-mode for \
    mafredri/zsh-async \
    kevinhwang91/zsh-tmux-capture

source $ZSH_LPLUG_DIR/completion.zsh
source $ZSH_LPLUG_DIR/misc.zsh
source $ZSH_LPLUG_DIR/color.zsh
source $ZSH_LPLUG_DIR/history.zsh
source $ZSH_LPLUG_DIR/alias-function.zsh
source $ZSH_LPLUG_DIR/theme.zsh
source $ZSH_LPLUG_DIR/git-prompt.zsh
source $ZSH_LPLUG_DIR/tmux.zsh
source $ZSH_LPLUG_DIR/fzf-plugin.zsh

# python prompt toolkit color depth
export PROMPT_TOOLKIT_COLOR_DEPTH=DEPTH_24_BIT

# less
export LESS=FKMRX

# ranger
if (( $+commands[ranger] )); then
    export RANGER_LOAD_DEFAULT_RC=FALSE
fi

# neovim
if (( $+commands[nvim] )); then
    export EDITOR=nvim
    export MANPAGER='nvim +Man!'
fi

# bat
if (( $+commands[bat] )); then
    export BAT_THEME=TwoDark
    export BAT_STYLE=plain
fi

# git pager
if (( $+commands[delta] )); then
    export GIT_PAGER=$(printf '%s ' delta -n --syntax-theme=TwoDark -w 1 \
        --minus-style=\"syntax #450a15\" --minus-emph-style=\"syntax #600818\" \
        --plus-style=\"syntax #0b4820\" --plus-emph-style=\"syntax #175c2e\" \
        --hunk-header-style=\"syntax bold\" --hunk-header-decoration-style=\"black box\" \
        --file-style=\"yellow italic\" --file-decoration-style=\"yellow ul\" \
        --line-numbers-zero-style=\"#4b5263\" \
        --line-numbers-left-format=\"{nm:^4} \" --line-numbers-right-format=\"{np:^4}  \")
fi
